version: '3.9'

services:
    postgres:
        image: postgres
        environment:
            POSTGRES_DB: store_dev
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '5432:5432'
        env_file:
            - .env
        volumes:
            - 'postgres:/var/lib/postgresql/data'

volumes:
    postgres:
